# Generated by Django 4.2.3 on 2023-07-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_all_images_userhistory_rejectedimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interstedimages',
            name='image_name',
        ),
    ]
