# Generated by Django 4.2.3 on 2023-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_remove_interstedimages_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interstedimages',
            name='visit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
