# Generated by Django 4.2.3 on 2023-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_interstedimages_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='is_reject',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='is_selected',
            field=models.BooleanField(default='True'),
        ),
    ]
